import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 800 } })
p.on('pageerror', (e) => console.log('EXC:', e.message))
await p.goto('http://localhost:5173/?debugOffice=1', { waitUntil: 'networkidle' })
await p.locator('.office-launch__button').waitFor({ state: 'attached' })
await p.locator('.office-launch__button').scrollIntoViewIfNeeded()
await p.locator('.office-launch__button').click()
await p.waitForTimeout(6000)
console.log('url:', p.url())
console.log('office-experience:', await p.locator('.office-experience').count())
console.log('cam:', await p.evaluate(() => typeof window.__officeCam))
console.log('scene:', await p.evaluate(() => typeof window.__officeScene))
console.log('debug text:', await p.locator('.office-debug code').innerText({ timeout: 3000 }).catch(() => 'NONE'))
await b.close()
